### ISSUE TITLE
[FR] - Adding problem sensor

### ISSUE THREAD

**Issue by robinostlund** [Thomas55555/aioautomower#241]
Hi,
Just wondering if there is any plans on adding the problem sensor to the real component i HASS? I have alot of automations connected to this one so it would be nice to have it in the real one before i migrate.

Thanks for an awesome work.

/ R

**Comment by Thomas55555** [comment]
Hi,
please don't ask here for features in other repositories.
But there will be no problem sensor. There is an error sensor and a restricted reason sensor, like mentioned in the docs.
