### ISSUE TITLE
Add support for StartInWorkArea

### ISSUE THREAD

**Issue by 2ndalpha** [Thomas55555/aioautomower#320]
I have Husqvarna 410XE NERA which has multiple work areas configured. From the Automower app I have to choose the work area it will operate in. In the API the action is StartInWorkArea

**Comment by Thomas55555** [comment]
You can test it with version 2024.6.0b0. Let me know, if it works.

**Comment by 2ndalpha** [comment]
Thank you 🙏 
I will test it in few days and come back to you

**Comment by 2ndalpha** [comment]
@Thomas55555 copy-pasting from Swagger has resulted a typo: Instead of `StartInMWorkArea` it should be `StartInWorkArea`. Remove the "M".

Unrelated to this change but in case of a 400 response the library does not log out the response body which complicated debugging.

**Comment by Thomas55555** [comment]
Should Work in 2024.6.0b1. please try again.
Anorher question: where so you get the Work area IDS from? Can you See them in the mobile App?

**Comment by 2ndalpha** [comment]
Thank you! It works.

Work areas are part of mower attributes.
Here are mine:

> MowerAttributes(system=System(name='Ukerdis', model='Husqvarna Automower® 410XE NERA', serial_number=123456), battery=Battery(battery_percent=100), capabilities=Capabilities(headlights=True, work_areas=True, position=True, stay_out_zones=True), mower=Mower(mode='MAIN_AREA', activity='NOT_APPLICABLE', state='IN_OPERATION', error_code=0, error_key=None, error_datetime=None, error_datetime_naive=None), calendar=Tasks(tasks=[], events=[]), planner=Planner(next_start_datetime=None, next_start_datetime_naive=None, override=Override(action='FORCE_MOW'), restricted_reason='NOT_APPLICABLE'), metadata=Metadata(connected=True, status_dateteime=datetime.datetime(2024, 6, 7, 17, 20, 31, 90000, tzinfo=datetime.timezone.utc)), positions=[Positions(latitude=1234, longitude=1234)], settings=Settings(headlight=Headlight(mode='ALWAYS_OFF'), cutting_height=9), statistics=Statistics(cutting_blade_usage_time=259143, number_of_charging_cycles=31, number_of_collisions=2336, total_charging_time=162112, total_cutting_time=259143, total_drive_distance=115011, total_running_time=273835, total_searching_time=4024), stay_out_zones=None, work_areas={17403: WorkArea(name='Backyard', cutting_height=44), 11029: WorkArea(name='Front yard', cutting_height=37)})
