### ISSUE TITLE
HA question - custom_command

### ISSUE THREAD

**Issue by markxroberts** [Thomas55555/aioautomower#503]
Hi
Are there any plans to reintroduce custom_command function in the HA core integration?
I use this for calendar setting, especially around DST changes.
Thanks
Mark

**Comment by Thomas55555** [comment]
Hi Mark,
no. Just sending a blob of data is not wanted by HA core.

**Comment by markxroberts** [comment]
Hi
That's a great shame.  Especially as actions such as ```mqtt.publish``` can take a very large json payload.
Is there any way to access the command within the library from Home Assistant?
Thanks
Mark

**Comment by markxroberts** [comment]
Understood, thanks very much for the explanation.  it makes sense to me, even if it means more work writing some more automations!
