### ISSUE TITLE
Husqvanrna API v2 (v1 deprecated)

### ISSUE THREAD

**Issue by petitpiton** [Thomas55555/aioautomower#542]
Husqvarna are retiring the current API wef 28 Feb 2025. They are replacing with a new version which is available from 20 December 2024. This will be a breaking change for this integration.
Raising for info.
https://app.qa-developer-portal.dss.husqvarnagroup.net/news/added-new-event-format

**Comment by Thomas55555** [comment]
Three is already a discussion about it #541
