### ISSUE TITLE
TypeError in python 3.8

### ISSUE THREAD

**Issue by gruberth** [Thomas55555/aioautomower#80]
Hello,

I am using your package as a communication base in a plugin to interface automowers and the SmarthomeNG home automation system. Since the minimum required python version there is 3.8 I had to set the aioautomower version in the requirements.txt of the plugin to 2022.3.1. Because after this version you added a line in your code that works only on python 3.9 anymore. 

But since now husqvarna changed the login to the api again, I have to update and use the logincc() function wich is only available in the newer versions of aioautomower. 

This is the error I get on python 3.8:
```
> Traceback (most recent call last):
>   File "/usr/local/smarthome/lib/plugin.py", line 548, in __init__
>     exec("import {0}".format(classpath))
>   File "<string>", line 1, in <module>
>   File "/usr/local/smarthome/plugins/husky2/__init__.py", line 38, in <module>
>     import aioautomower
>   File "/home/administrator/.local/lib/python3.8/site-packages/aioautomower/__init__.py", line 2, in <module>
>     from .rest import *
>   File "/home/administrator/.local/lib/python3.8/site-packages/aioautomower/rest.py", line 154, in <module>
>     class GetMowerData:
>   File "/home/administrator/.local/lib/python3.8/site-packages/aioautomower/rest.py", line 170, in GetMowerData
>     async def async_mower_state(self) -> list[dict]:
> TypeError: 'type' object is not subscriptable
```

Is there any possibility to fix this for 3.8? Maybe by adding `from __future__ import annotations` or something else..

Thanks

**Comment by gruberth** [comment]
Adding `from __future__ import annotations` as first import in rest.py completely fixes this error. Maybe you can add this in the next versions.

**Comment by Thomas55555** [comment]
@gruberth: Please let me know, when I can drop 3.8 support.

**Comment by gruberth** [comment]
End of offical support for python 3.8 is october 2024, so i think the core of SmarthomeNg will keep it as the minimum version till then.

( https://smarthomeng.github.io/smarthome/installation/anforderungen.html#minimum-python-version )

For me it is oke if you end the support for 3.8 in your further versions. I will find a fix for my plugin or raise the minimum version for it to 3.9 meanwhile the core stays at 3.8.

Thanks for your care
