### ISSUE TITLE
Refresh token in session

### ISSUE THREAD

**Issue by gruberth** [Thomas55555/aioautomower#81]
Using the login with client credentials does not refresh the token in a session.

[Api Doc](https://developer.husqvarnagroup.cloud/docs/api):
> Note that a refresh_token is not sent back when logging in with client credentials. Use the access_token for as long as it is valid. After it have been invalid or expired, login with the client credentials again to get a new access token.

Therefore the AutomowerSession.refresh_token() method should be adapted, to make the full login procedure at token expiration.

**Comment by Thomas55555** [comment]
This method is only for a single login. I've update the description. Maybe it's better to use Authorization Code Grant instead of die Client Credentials Grant? Because ACG is the preferred method of Husqvarna:

[Api Doc](https://developer.husqvarnagroup.cloud/docs/api):
> The client_credentials grant is intended only for your own user, the authorization_code grant type is a bit more secure and intended for everyone else that wants to use your application.

**Comment by gruberth** [comment]
You are right.
But using the ACG seems not to be verry suitable or comfortable for an automated (and mostly network internal only) system without a possibility for a redirect. 

If I get the token once using the ACG, does then on every token refresh the response contain the `refresh_token`? So if I keep track of the entire token response (also on reboot of the system), I can always refresh my token without a new ACG?

Thanks

**Comment by Thomas55555** [comment]
Yes

**Comment by Thomas55555** [comment]
With release 2023.12.0 the token is not handled by the library anymore and you can now individually create your token.

**Comment by gruberth** [comment]
Thats great, I am going to implement it as soon as possible.
Thanks for your care.
