### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by fmarzocca** [Thomas55555/aioautomower#86]
Running v. 2022.9.0 on python 3.9.2 (raspberry debian bullseye).

I have imported your first Example, but I am getting this error:

```
Traceback (most recent call last):
  File "/home/boss/.node-red/assets/./testMower.py", line 16, in <module>
    from aioautomower import GetAccessToken, GetMowerData, Return
ImportError: cannot import name 'GetAccessToken' from 'aioautomower' (/usr/local/lib/python3.9/dist-packages/aioautomower/__init__.py)
```

**Comment by Thomas55555** [comment]
Is it working now, and can this be closed?

**Comment by fmarzocca** [comment]
Yes. Thanks.


- Sent from my mobile phone. Sorry for typos -

Il Lun 5 Dic 2022, 12:54 Thomas55555 ***@***.***> ha scritto:
