### ISSUE TITLE
Error in line 68

### ISSUE THREAD

**Issue by theseant** [Thomas55555/aioautomower#87]
Thanks for sharing your nice code.

I have installed it and am running it on a raspberry Pi 4 (PiOS, ARM64)

When I run the programme I get an error:
"  File "/home/pi/python/automower.py", line 68
    self.command_type
    ^
SyntaxError: invalid syntax"

I have tried writing a python programme to call the API requests myself using Requests but I run into trouble with the syntax of the mower request but I can get an access token -s the ID and secret seem to be OK. So any help would be appreciated...

Sean

**Comment by theseant** [comment]
Actually, having looked at this again, Im not sure what .py I should run. Cutting and pasting from the example in the read,me didnt work but perhaps I should have thought this through a little better. 

I have downloaded the whole archive now but I still can't work out which file to run first and would welcome a pointer here.

**Comment by Thomas55555** [comment]
Hi, there was an error in the readme. I've fixed this with #88
Maybe you can tray this again. Otherwise, share your `automower.py` to identify the issue
